In [17]:
import pandas as pd
import numpy as np

course_data = pd.read_csv("courses.csv")

course_data = course_data.dropna(how="any")
print(course_data)


             Course                Instructor    Cap     Location  \
0     MAT-012 - 001       Tavernetti, William  350.0     TLC 1020   
1     MAT-012 - 002             Burke, Korana  325.0     TLC 1020   
2    MAT-017A - A01               Chan, Addie   33.0     TLC 1020   
4    MAT-017A - A02               Chan, Addie   33.0     TLC 1020   
6    MAT-017A - A03               Chan, Addie   33.0     TLC 1020   
..              ...                       ...    ...          ...   
435  MAT-235A - 001            Gravner, Janko   40.0   PHYSIC 140   
437   MAT-246 - 001        Kuperberg, Gregory   20.0   WELLMN 203   
438  MAT-258B - 001           De Loera, Jesus   20.0   WELLMN 201   
439   MAT-280 - 001  Sherman-Bennett, Melissa   20.0  BAINER 1128   
448   MAT-390 - 001               Zarkh, Anna   40.0   PHYSIC 140   

                Times  
0    MWF 1210-0100 PM  
1    MWF 0210-0300 PM  
2    MWF 0110-0200 PM  
4    MWF 0110-0200 PM  
6    MWF 0110-0200 PM  
..                ...  
435

In [18]:
course_data["helper"] = course_data["Course"].str.extract(r"MAT-(\d{3})")
course_data["helper"] = course_data["helper"].astype(int)
course_data["Cap"] = course_data["Cap"].astype(int)
course_data = course_data[course_data["helper"] >= 100]
course_data = course_data.drop(columns=["helper"])
course_data = course_data.reset_index(drop=True)
course_data.index = course_data.index + 1
print(course_data)
course_data.to_csv("data/courses.csv")

            Course                Instructor  Cap      Location  \
1    MAT-108 - A01           Siebert, Oliver   35   WELLMAN 230   
2    MAT-108 - A02           Siebert, Oliver   35   WELLMAN 230   
3    MAT-108 - B01                   Liu, Fu   35     OLSON 250   
4    MAT-108 - B02                   Liu, Fu   35     OLSON 250   
5    MAT-108 - D01                   Liu, Fu   35     OLSON 223   
6    MAT-108 - D02                   Liu, Fu   35     OLSON 223   
7   MAT-115A - A01      Soshnikov, Alexander   30    HOAGLD 168   
8   MAT-115A - A02      Soshnikov, Alexander   30    HOAGLD 168   
9   MAT-115A - B01               Li, Junxian   30    HOAGLD 168   
10  MAT-115A - B02               Li, Junxian   30    HOAGLD 168   
11  MAT-118A - 001               Jacob, Adam   60    WELLMN 212   
12  MAT-119A - 001       Chaudhuri, Rishidev   70     OLSON 106   
13  MAT-127A - A01              Iyer, Sameer   30   WALKER 1320   
14  MAT-127A - A02              Iyer, Sameer   30   WALKER 132

In [19]:
rooms_data = pd.read_csv("rooms.csv")
rooms_data = rooms_data[rooms_data["Classroom List"].str.startswith("Wellman Hall")]
rooms_data = rooms_data.reset_index(drop=True)
rooms_data.index = rooms_data.index + 1
rooms_data.to_csv("data/rooms.csv")
print(rooms_data)

      Classroom List  Capacity
1   Wellman Hall 129        23
2   Wellman Hall 235        24
3   Wellman Hall 105        25
4   Wellman Hall 107        25
5   Wellman Hall 101        25
6   Wellman Hall 103        25
7   Wellman Hall 203        27
8    Wellman Hall 27        28
9   Wellman Hall 127        29
10  Wellman Hall 123        29
11  Wellman Hall 233        32
12  Wellman Hall 229        34
13    Wellman Hall 1        35
14    Wellman Hall 3        35
15    Wellman Hall 5        35
16  Wellman Hall 109        35
17    Wellman Hall 7        35
18  Wellman Hall 205        35
19   Wellman Hall 25        36
20  Wellman Hall 201        40
21  Wellman Hall 207        41
22  Wellman Hall 115        56
23  Wellman Hall 212        70
24  Wellman Hall 230        80
25  Wellman Hall 119        82
26  Wellman Hall 202        87
27  Wellman Hall 226       102
28  Wellman Hall 216       102
29  Wellman Hall 234       104
30   Wellman Hall 26       105
31    Wellman Hall 6       105
32  Well

In [20]:
courses = course_data.apply(lambda row: tuple(row), axis= 1).to_numpy()
rooms = rooms_data.apply(lambda row: tuple(row), axis=1).to_numpy()
m = courses.shape[0]
n = rooms.shape[0]
conflict_cap_array = np.zeros((m, n))

for i, c in enumerate(courses):
    for j, r in enumerate(rooms):
        if c[2] > r[1]:
            conflict_cap_array[i, j] = 0
        else:
            conflict_cap_array[i, j] = 1

np.set_printoptions(threshold=np.inf)

conflict_array = conflict_cap_array.astype(int)
time = np.array([i for i in range(8, 18)])
print(conflict_array)
print(time)    

[[0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 

In [21]:
conflict_instructor_list = []
for i in range(m):
    for j in range(i + 1, m):
        if courses[i][1] == courses[j][1]:
            conflict_instructor_list.append((i, j))

print(conflict_instructor_list) 

[(0, 1), (2, 3), (2, 4), (2, 5), (3, 4), (3, 5), (4, 5), (6, 7), (6, 23), (6, 24), (7, 23), (7, 24), (8, 9), (10, 40), (12, 13), (12, 14), (12, 15), (12, 37), (13, 14), (13, 15), (13, 37), (14, 15), (14, 37), (15, 37), (16, 17), (18, 19), (20, 22), (23, 24), (25, 26), (25, 42), (26, 42), (27, 28), (30, 31), (32, 33), (35, 44)]


In [22]:
from pyscipopt import Model, quicksum
from itertools import product

def solve(courses: np.ndarray, rooms: np.ndarray, time: np.ndarray, M: np.ndarray):
    C = courses.shape[0]
    R = rooms.shape[0]
    T = time.shape[0]
    model = Model()
    x = {}
    y = {}
    valid_indices = np.argwhere(M == 1)
    for c, r in valid_indices:
        for t in range(T):
            x[(c, r, t)] = model.addVar(name=f"x_{c}_{r}_{t}", vtype="B")
    

    for r in range(R):
        y[r] = model.addVar(name=f"y_{r}", vtype="B")

    
    for c in range(C):
        model.addCons(quicksum(x[(c, r, t)] 
                        for r in range(R)
                        for t in range(T)
                        if M[c, r] == 1) == 1)
    
    for r, t in product(range(R), range(T)):
        model.addCons(quicksum(x[(c, r, t)]
                        for c in range(C)
                        if M[c, r] == 1) <= 1)
        
    for r in range(R):
        model.addCons(quicksum(x[(c, r, t)]
                          for c in range(C)
                          for t in range(T)
                          if M[c, r] == 1) <= (C*T + 1) * y[r])
        
    for t in range(T):
        for c1, c2 in conflict_instructor_list:
            model.addCons(quicksum(x[c1, r, t] for r in range(R) if M[c1, r] == 1) +
                          quicksum(x[c2, r, t] for r in range(R) if M[c2, r] == 1) 
                          <= 1)
        
    model.setObjective(quicksum(y[r] for r in range(R)), sense="minimize")
    model.optimize()
    return model, x

model, x = solve(courses, rooms, time, conflict_cap_array)


presolving:
   (0.0s) running MILP presolver
   (0.0s) MILP presolver found nothing
(round 1, exhaustive) 0 del vars, 0 del conss, 0 add conss, 0 chg bounds, 0 chg sides, 34 chg coeffs, 771 upgd conss, 0 impls, 737 clqs
(round 2, medium)     0 del vars, 34 del conss, 1017 add conss, 0 chg bounds, 0 chg sides, 34 chg coeffs, 771 upgd conss, 0 impls, 11923 clqs
   (0.1s) probing: 51/10204 (0.5%) - 0 fixings, 0 aggregations, 0 implications, 0 bound changes
   (0.1s) probing aborted: 50/50 successive totally useless probings
   (0.1s) symmetry computation started: requiring (bin +, int +, cont +), (fixed: bin -, int -, cont -)
   (0.2s) symmetry computation finished: 67 generators found (max: 1500, log10 of symmetry group size: 38.09) (symcode time: 0.05)
dynamic symmetry handling statistics:
   orbitopal reduction:       no components
   orbital reduction:         no components
   lexicographic reduction:   no permutations
handled 1 out of 1 symmetry components
(round 3, exhaustive) 39 de

In [23]:
from tabulate import tabulate

res = {}
for (c, r, t), var in x.items():
    if model.getVal(var) > 0.5:
        res[(r, t)] = c
    
rows = sorted({r for r, _ in res.keys()})
cols = sorted({t for _, t in res.keys()})

table = []
for r in rows:
    row = [f"{rooms[r][0]}\nCapacity = {rooms[r][1]}"]
    for t in cols:
        if res.get((r, t)) == None:
            row.append("")
        else:
            row.append(f"{courses[res.get((r, t))][0]}\nProf:{courses[res.get((r, t))][1]}\nEnrollment = {courses[res.get((r, t))][2]}")
    table.append(row)

headers = [""] + list(time[cols])
print(tabulate(table, headers=headers, tablefmt="grid"))

+------------------+-------------------------------+---------------------------+---------------------+---------------------+-------------------------+----------------------+---------------------------+---------------------------+---------------------+--------------------------+
|                  | 8                             | 9                         | 10                  | 11                  | 12                      | 13                   | 14                        | 15                        | 16                  | 17                       |
+==================+===============================+===========================+=====================+=====================+=========================+======================+===========================+===========================+=====================+==========================+
| Wellman Hall 5   | MAT-280 - 001                 | MAT-127C - A02            | MAT-108 - D02       | MAT-135A - B01      | MAT-215A - 001          | MAT-108 - A0